name: Run Appium Tests on Android Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-appium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium
      run: |
        npm install -g appium
        appium -v

    - name: Run Emulator and Execute Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: pixel
        force-avd-creation: true
        emulator-options: -no-window -no-audio -gpu swiftshader_indirect -no-snapshot-save
        disable-animations: true
        script: |
          echo "Waiting for emulator to fully boot..."
          adb wait-for-device
          
          boot_completed=""
          retry=0
          max_retries=15
          while [[ "$boot_completed" != "1" && $retry -lt $max_retries ]]; do
            sleep 5
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "boot_completed=$boot_completed (attempt $((retry+1)))"
            retry=$((retry+1))
          done

          if [[ "$boot_completed" != "1" ]]; then
            echo "Emulator failed to boot after $max_retries attempts."
            exit 1
          fi

          echo "Emulator is ready. Starting Appium..."
          nohup appium > appium.log 2>&1 &
          sleep 10

          echo "Running tests with Maven..."
          mvn clean test

