name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-instrumented-tests:
    name: Run Android Appium Tests with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up Node.js (for Appium server)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium and dependencies
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2

      - name: Start Android Emulator and run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: pixel
          ram-size: 2048M
          heap-size: 512M
          emulator-options: "-no-window -no-audio -gpu swiftshader_indirect -no-snapshot-save"
          disable-animations: true
          script: |
            appium --log appium.log --base-path /wd/hub &
            sleep 15
            mvn clean test
