name: Run Appium Android Tests on Emulator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Appium and Required Drivers
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_8
          avd-name: Pixel_8
          emulator-options: -no-snapshot-save -no-window
          disable-animations: true
          script: echo "Emulator is ready"

      - name: Start Appium Server
        run: |
          nohup appium > appium.log 2>&1 &
          sleep 10
          echo "Appium server started."

      - name: Grant Execution Permissions for Maven
        run: chmod +x mvnw

      - name: Run Tests
        run: ./mvnw clean test


