name: Run Appium Tests on Self-Hosted Runner

on:
  push:
    branches:
      - rahul
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Appium (if not installed globally)
        run: npm install -g appium


      - name: Verify Android Device Connection
        run: adb devices

      - name: Run Maven Tests
        run: mvn clean test
