name: Run Appium Tests on Android Emulator

on:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium and Drivers
      run: |
        npm set progress=false
        npm config set loglevel warn
        npm install -g appium
        appium driver install uiautomator2

    - name: Start Appium Server
      run: |
        appium --base-path / --log-level info > appium.log 2>&1 &
        sleep 10

    - name: Run Android Emulator and Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: pixel
        emulator-options: "-no-window -no-audio"
        script: |
          adb wait-for-device
          echo "⏳ Waiting for emulator to fully boot..."
          while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 5; done
          echo "✅ Emulator is ready."
          adb shell input keyevent 82
          mvn clean test


